package com.limosys.dblib.vladtest.da;

import com.borland.dx.sql.dataset.Database;
import com.borland.dx.dataset.StorageDataSet;
import java.util.Hashtable;
import com.borland.dx.sql.dataset.ProcedureDataSet;
import com.borland.dx.sql.dataset.QueryDataSet;
import com.borland.dx.dataset.Column;
import com.borland.dx.dataset.DataSetException;
import com.borland.dx.sql.dataset.ResolutionException;
import com.borland.dx.dataset.Variant;
import com.borland.dx.dataset.CalcFieldsListener;
import java.util.TooManyListenersException;
import java.math.BigDecimal;
import java.sql.Time;
import java.util.Date;
import java.sql.Timestamp;
import java.util.GregorianCalendar;
import com.limosys.jlimoobject.JLimoObject;
import com.limosys.dblib.jlimoobject.utils.ObjectUtils;
import com.limosys.jlimoobject.ValidateResult;
import com.limosys.jlimoobject.SaveException;
import com.borland.dx.dataset.*;
import java.math.MathContext;
import com.limosys.dbaccess.DbAccessListener;
import com.limosys.jlimoobject.JLimoObjectProperty;
import com.limosys.jlimoobject.JLimoObjectSearchProperty;
import com.limosys.dbaccess.vladtest.T6467063785Access;
import com.limosys.dbaccess.vladtest.T6467063785AccessList;

/**
 * <B>WARNING:</B> Class generated by JLimoObjectDesigner.  Do not make any changes, as they will be lost next time the
 * file is regenerated.  Any custom logic should be included in descending classes.
 *
 */
public abstract class T6467063785DataAccess extends JLimoObject {

  public enum T6467063785AccessType {
    NONE,
    ONEREC,
    LIST
  }

  public enum T6467063785DataSetId {
    ONEREC_DEFAULT (T6467063785AccessType.ONEREC),
    LIST_DEFAULT (T6467063785AccessType.LIST);

    private T6467063785AccessType accessType;
    private T6467063785DataSetId(T6467063785AccessType accessType) {
      this.accessType = accessType;
    }
    public T6467063785AccessType getAccessType() {
      return this.accessType;
    }
  }

  public abstract void synchronizeWithMainDataSet();
  protected abstract void addCalculatedColumns();
  protected abstract boolean allowAccessTypeChange(T6467063785AccessType accessType);


  private void initProps() {
    try {
      htObjProps.put("Name", new JLimoObjectProperty("Name", this.getClass().getMethod("colName"), Variant.STRING));
      htObjProps.put("CompanyName", new JLimoObjectProperty("CompanyName", this.getClass().getMethod("colCompanyName"), Variant.STRING));
      htObjProps.put("Id", new JLimoObjectProperty("Id", this.getClass().getMethod("colId"), Variant.INT));
    } catch (SecurityException ex) {
    } catch (NoSuchMethodException ex) {
    }
  }

protected void changesLog_Prepare() {}

protected void changesLog_Save() {}

public void transaction_BeforeSave() throws SaveException {
  ValidateResult vr = validate();
  if (!vr.isValid()) throw new SaveException(vr);
  changesLog_Prepare();
}

public void transaction_AfterSave() {
  changesLog_Save();
}


private void initSearchProps() {
  try {
    htObjSearchProps = new Hashtable<String, JLimoObjectSearchProperty>();
  } catch (SecurityException ex) {
  }
}


// *** Constructors: ***
public T6467063785DataAccess() {
  initProps();
  initSearchProps();
}
public T6467063785DataAccess(T6467063785AccessType accessType, boolean useDefaultInstance) {
  initProps();
  initSearchProps();
  setAccessType(accessType, useDefaultInstance);
}
public T6467063785DataAccess(T6467063785AccessType accessType, Database db) {
  initProps();
  initSearchProps();
  setAccessType(accessType, db);
}
public T6467063785DataAccess(T6467063785AccessType accessType, StorageDataSet[] dsArr) {
  initProps();
  initSearchProps();
  setAccessType(accessType, dsArr);
}

protected ReadWriteRow rwRow;
protected T6467063785DataAccess(T6467063785AccessType accessType, ReadWriteRow rwRow) {
  if (accessType == T6467063785AccessType.NONE && rwRow == null)
    throw new DataSetException("Can't use this constructor with T6467063785AccessType.NONE or null rwRow.");
  this.rwRow = rwRow;
  switch (accessType) {
    case ONEREC:
      curAccessType = T6467063785AccessType.ONEREC;
      break;
    case LIST:
      curAccessType = T6467063785AccessType.LIST;
      break;
    default:
      curAccessType = T6467063785AccessType.NONE;
  }
}


// *** setAccessType Methods: ***
private T6467063785AccessType curAccessType = T6467063785AccessType.NONE;
public T6467063785AccessType getAccessType() {
    return curAccessType;
}

protected StorageDataSet[] curDataSets;
private void setCurrentDataSets() {
  T6467063785DataSetId[] dsIds = getDataSetIds(curAccessType);
  curDataSets = new StorageDataSet[dsIds.length];
  for (int i=0; i<dsIds.length; i++) {
        curDataSets[i] = getDataSet(dsIds[i]);
  }
  addCalculatedColumns();
  updatePropertiesAndEvents();
}

protected void setAccessType(T6467063785AccessType accessType, boolean useDefaultInstance) {
  setAccessType(accessType, useDefaultInstance, null);
}
protected void setAccessType(T6467063785AccessType accessType, boolean useDefaultInstance, DbAccessListener dbAccessListener) {
  if (!allowAccessTypeChange(accessType)) {
    throw new DataSetException("Can't change Access Type to " + accessType.toString());
  }
  htDataSets.clear();
  switch (accessType) {
  case ONEREC:
    T6467063785Access aT6467063785Access0 = (useDefaultInstance ? T6467063785Access.getInstance() : new T6467063785Access());
    if (dbAccessListener!=null) {
      aT6467063785Access0.addDbAccessListener(dbAccessListener);
    }
    htDataSets.put(T6467063785DataSetId.ONEREC_DEFAULT, aT6467063785Access0.getViewDataSet());
    curAccessType = T6467063785AccessType.ONEREC;
    break;
  case LIST:
    T6467063785AccessList aT6467063785AccessList1 = (useDefaultInstance ? T6467063785AccessList.getInstance() : new T6467063785AccessList());
    if (dbAccessListener!=null) {
      aT6467063785AccessList1.addDbAccessListener(dbAccessListener);
    }
    htDataSets.put(T6467063785DataSetId.LIST_DEFAULT, aT6467063785AccessList1.getViewDataSet());
    curAccessType = T6467063785AccessType.LIST;
    break;
  default:
      curAccessType = T6467063785AccessType.NONE;
  }
  setCurrentDataSets();
}

protected void setAccessType(T6467063785AccessType accessType, Database db) {
  setAccessType(accessType, db, null);
}

protected void setAccessType(T6467063785AccessType accessType, Database db, DbAccessListener dbAccessListener) {
  if (!allowAccessTypeChange(accessType)) {
    throw new DataSetException("Can't change Access Type to " + accessType.toString());
  }
  htDataSets.clear();
  switch (accessType) {
    case ONEREC:
      T6467063785Access accsCls0_0 = new T6467063785Access(db);
      if (dbAccessListener!=null) {
        accsCls0_0.addDbAccessListener(dbAccessListener);
      }
      htDataSets.put(T6467063785DataSetId.ONEREC_DEFAULT, accsCls0_0.getViewDataSet());
      curAccessType = T6467063785AccessType.ONEREC;
      break;
    case LIST:
      T6467063785AccessList accsCls1_0 = new T6467063785AccessList(db);
      if (dbAccessListener!=null) {
        accsCls1_0.addDbAccessListener(dbAccessListener);
      }
      htDataSets.put(T6467063785DataSetId.LIST_DEFAULT, accsCls1_0.getViewDataSet());
      curAccessType = T6467063785AccessType.LIST;
      break;
    default:
      curAccessType = T6467063785AccessType.NONE;
  }
  setCurrentDataSets();
}

protected boolean setAccessType(T6467063785AccessType accessType, StorageDataSet[] dsArr) {
  if (!allowAccessTypeChange(accessType)) {
    throw new DataSetException("Can't change Access Type to " + accessType.toString());
  }
  htDataSets.clear();
  T6467063785DataSetId[] dsIds = getDataSetIds(accessType);
  if (dsArr==null || dsArr.length != dsIds.length) {
      curAccessType = T6467063785AccessType.NONE;
      setCurrentDataSets();
      return false;
  }

  switch (accessType) {
  case ONEREC:
    htDataSets.put(T6467063785DataSetId.ONEREC_DEFAULT, dsArr[0]);
    curAccessType = T6467063785AccessType.ONEREC;
    break;
  case LIST:
    htDataSets.put(T6467063785DataSetId.LIST_DEFAULT, dsArr[0]);
    curAccessType = T6467063785AccessType.LIST;
    break;
  default:
      curAccessType = T6467063785AccessType.NONE;
  }
  setCurrentDataSets();
  return true;
}


// *** Design Support Methods: ***
private StorageDataSet sdsNone = new StorageDataSet();
protected StorageDataSet getSdsNone() {
  return sdsNone;
}
protected Column[] getDesignColumns() {
  return sdsNone.getColumns();
}
protected Column[] getDesignColumns(T6467063785DataSetId dsId) {
  if (dsId.accessType!=curAccessType) return new Column[0];
  return getDataSet(dsId).getColumns();
}


// *** DataSet Methods: ***
public T6467063785DataSetId[] getDataSetIds(T6467063785AccessType accessType) {
  int size = 0;
  for (T6467063785DataSetId dsId : T6467063785DataSetId.values()) {
    if (dsId.getAccessType()==accessType) size++;
  }
  T6467063785DataSetId[] dsIdArr = new T6467063785DataSetId[size];
  int i = 0;
  for (T6467063785DataSetId dsId : T6467063785DataSetId.values()) {
    if (dsId.getAccessType()==accessType) dsIdArr[i++] = dsId;
  }
  return dsIdArr;
}

public StorageDataSet getDataSetMain() {
  if (curDataSets==null || curDataSets.length==0) {
    return null;
  } else {
    return curDataSets[0];
  }
}

public ReadWriteRow getReadWriteRow() {
  if (rwRow!=null) return rwRow;
  if (curAccessType==T6467063785AccessType.NONE) return null;
  StorageDataSet sds = getDataSetMain();
  if (getDataSetMain()==null || sds.rowCount()==0) return null;
  DataRow dr = new DataRow(sds);
  sds.getDataRow(dr);
  return dr;
}

private java.util.Hashtable<T6467063785DataSetId, StorageDataSet> htDataSets = new Hashtable<T6467063785DataSetId,StorageDataSet>();
public StorageDataSet getDataSet(T6467063785DataSetId dataSetId) {
  if (dataSetId.getAccessType()!=curAccessType) return null;
      return htDataSets.get(dataSetId);
}
protected void setDataSet(T6467063785DataSetId dataSetId, StorageDataSet dataSet) {
  htDataSets.put(dataSetId, dataSet);
}
protected void clearDataSet(T6467063785DataSetId dataSetId) {
  htDataSets.remove(dataSetId);
}

public void addNew() {
  if (!curDataSets[0].isOpen()) curDataSets[0].open();
  curDataSets[0].insertRow(false);
}

protected abstract ValidateResult validateRow(ReadWriteRow origRow);

public ValidateResult validate() {
  Post();
  int curRowNo = curDataSets[0].getRow();
  ValidateResult vr;
  DataSetView dsvUpdated = getDsvUpdated(curDataSets[0]);
  dsvUpdated.first();
  for (int i=0; i<dsvUpdated.getRowCount(); i++) {
    DataRow origRow = new DataRow(curDataSets[0]);
    curDataSets[0].getOriginalRow(dsvUpdated, origRow);
    curDataSets[0].goToRow(dsvUpdated);
    vr = validateRow(origRow);
    if (vr!=null && !vr.isValid()) {
      curDataSets[0].goToRow(dsvUpdated);
      dsvUpdated.close();
      return vr;
    }
    dsvUpdated.next();
  }
  dsvUpdated.close();
  DataSetView dsvInserted = getDsvInserted(curDataSets[0]);
  dsvInserted.first();
  for (int i=0; i<dsvInserted.getRowCount(); i++) {
    curDataSets[0].goToRow(dsvInserted);
    vr = validateRow(null);
    if (vr!=null && !vr.isValid() ) {
      curDataSets[0].goToRow(dsvInserted);
      dsvInserted.close();
      return vr;
    }
    dsvInserted.next();
  }
  dsvInserted.close();
  curDataSets[0].goToRow(curRowNo);
  return new ValidateResult();
}

public void saveChanges() throws SaveException {
  ValidateResult vr;
  if (curDataSets.length==0) return;
  if (curDataSets.length==1) {
    vr = validate();
    if( !vr.isValid() ) throw new SaveException(vr);
    try {
      changesLog_Prepare();
      curDataSets[0].saveChanges();
      changesLog_Save();
    } catch (ResolutionException ex) {
      throw new SaveException(ex.fillInStackTrace().toString(), ex.getDataSet());
    } catch (Exception ex) {
      throw new SaveException(ex.fillInStackTrace().toString());
    }
    return;
  }

  Database db = null;
  for (int i=0; i<curDataSets.length; i++) {
    Database curDb = null;
    if (curDataSets[i] instanceof ProcedureDataSet) {
      curDb = ((ProcedureDataSet)curDataSets[i]).getDatabase();
    } else if (curDataSets[i] instanceof QueryDataSet) {
      curDb = ((QueryDataSet)curDataSets[i]).getDatabase();
    }

    if (curDb==null) {
      db = null;
      break;
    } else if (db==null) {
      db = curDb;
    } else if (curDb!=db) {
      db = null;
      break;
    }
  }

  try {
    changesLog_Prepare();
    vr = validate();
    if (!vr.isValid())
      throw new SaveException(vr);
    if (db == null) {
      for (int i = 0; i < curDataSets.length; i++) {
        curDataSets[i].saveChanges();
      }
    } else {
      db.saveChanges(curDataSets);
    }
    changesLog_Save();
  } catch (ResolutionException ex) {
    throw new SaveException(ex.fillInStackTrace().toString(), ex.getDataSet());
  } catch (Exception ex) {
    throw new SaveException(ex.fillInStackTrace().toString());
  }
}

public void RefreshDataSets() {
  if (curDataSets.length==0) return;
  for (int i=0; i<curDataSets.length; i++) {
      curDataSets[i].refresh();
  }
}

public void Post() {
  if (curDataSets.length==0) return;
  for (int i=0; i<curDataSets.length; i++) {
      curDataSets[i].post();
  }
}

public boolean isEmptyDataSet() {
  if (curDataSets.length==0) return true;
  if (!curDataSets[0].isOpen()) curDataSets[0].open();
  return curDataSets[0].isEmpty();
}

// *** Private Helper Methods: ***
protected DataSetException getPropertyNotAvailableException(String propName) {
  return new DataSetException(DataSetException.COLUMN_NOT_IN_ROW,
                              "Property " + propName + " not available in T6467063785AccessType." + curAccessType);
}

protected void updatePropertiesAndEvents() {
  if (sdsNone==null) return;
  if (curDataSets==null) return;
  CalcFieldsListener calcFldsLstnr = sdsNone.getCalcFieldsListener();
  for (int i=0; i<curDataSets.length; i++) {
    StorageDataSet sds = curDataSets[i];
      for(Column col : sds.getColumns() ) {
        if (col.getCalcType() == CalcType.CALC) {
          if (calcFldsLstnr != null) {
            try {
              sds.addCalcFieldsListener(calcFldsLstnr);
              break;
            } catch (TooManyListenersException ex) {}
          }
        }
      }
    }
    for (int j=0; j<sdsNone.getColumns().length; j++) {
      Column colNone = sdsNone.getColumn(j);
      Column col = getColumnByProperty(colNone.getColumnName());
      if (col!=null) {
        col.setCaption(colNone.getCaption());
      }
    }
  }

// Name:
  public boolean isNameNull() {
    switch (curAccessType) {
    case ONEREC:
      return rwRow==null ? curDataSets[0].isNull("NAME") : rwRow.isNull("NAME");
    case LIST:
      return rwRow==null ? curDataSets[0].isNull("NAME") : rwRow.isNull("NAME");
    default:
      throw getPropertyNotAvailableException("Name");
    }
  }
  public void setNameNull() {
    switch (curAccessType) {
    case ONEREC:
      if (rwRow==null) {
        curDataSets[0].setAssignedNull("NAME");
      } else {
        rwRow.setAssignedNull("NAME");
      }
      break;
    case LIST:
      if (rwRow==null) {
        curDataSets[0].setAssignedNull("NAME");
      } else {
        rwRow.setAssignedNull("NAME");
      }
      break;
    default:
      throw getPropertyNotAvailableException("Name");
    }
  }
  public String getName() {/// ## 1
    if (isNameNull()) return null;
    switch (curAccessType) {
    case ONEREC:
      return rwRow==null ? curDataSets[0].getString("NAME") : rwRow.getString("NAME");
    case LIST:
      return rwRow==null ? curDataSets[0].getString("NAME") : rwRow.getString("NAME");
    default:
      throw getPropertyNotAvailableException("Name");
    }
  }
  public void setName(String name) {/// ## 2
    if (name==null) {
      setNameNull();
      return;
    }
    switch (curAccessType) {
    case ONEREC:
      if (rwRow==null) {
        curDataSets[0].setString("NAME", name);
      } else {
        rwRow.setString("NAME", name);
      }
      break;
    case LIST:
      if (rwRow==null) {
        curDataSets[0].setString("NAME", name);
      } else {
        rwRow.setString("NAME", name);
      }
      break;
    default:
      throw getPropertyNotAvailableException("Name");
    }
  }
  public Column colName() {
    switch (curAccessType) {
    case ONEREC:
      return (rwRow==null ? curDataSets[0].getColumn("NAME") : rwRow.getColumn("NAME"));
    case LIST:
      return (rwRow==null ? curDataSets[0].getColumn("NAME") : rwRow.getColumn("NAME"));
    case NONE:
      if (sdsNone.hasColumn("Name")==null) {
        Column col = new Column();
        col.setCaption("Name");
        col.setColumnName("Name");
        col.setDataType(com.borland.dx.dataset.Variant.STRING);
        sdsNone.addColumn(col);
      }
      return sdsNone.getColumn("Name");
    default:
      return null;
    }
  }

// CompanyName:
  public boolean isCompanyNameNull() {
    switch (curAccessType) {
    case ONEREC:
      return rwRow==null ? curDataSets[0].isNull("COMPANY_NAME") : rwRow.isNull("COMPANY_NAME");
    case LIST:
      return rwRow==null ? curDataSets[0].isNull("COMPANY_NAME") : rwRow.isNull("COMPANY_NAME");
    default:
      throw getPropertyNotAvailableException("CompanyName");
    }
  }
  public void setCompanyNameNull() {
    switch (curAccessType) {
    case ONEREC:
      if (rwRow==null) {
        curDataSets[0].setAssignedNull("COMPANY_NAME");
      } else {
        rwRow.setAssignedNull("COMPANY_NAME");
      }
      break;
    case LIST:
      if (rwRow==null) {
        curDataSets[0].setAssignedNull("COMPANY_NAME");
      } else {
        rwRow.setAssignedNull("COMPANY_NAME");
      }
      break;
    default:
      throw getPropertyNotAvailableException("CompanyName");
    }
  }
  public String getCompanyName() {/// ## 1
    if (isCompanyNameNull()) return null;
    switch (curAccessType) {
    case ONEREC:
      return rwRow==null ? curDataSets[0].getString("COMPANY_NAME") : rwRow.getString("COMPANY_NAME");
    case LIST:
      return rwRow==null ? curDataSets[0].getString("COMPANY_NAME") : rwRow.getString("COMPANY_NAME");
    default:
      throw getPropertyNotAvailableException("CompanyName");
    }
  }
  public void setCompanyName(String companyName) {/// ## 2
    if (companyName==null) {
      setCompanyNameNull();
      return;
    }
    switch (curAccessType) {
    case ONEREC:
      if (rwRow==null) {
        curDataSets[0].setString("COMPANY_NAME", companyName);
      } else {
        rwRow.setString("COMPANY_NAME", companyName);
      }
      break;
    case LIST:
      if (rwRow==null) {
        curDataSets[0].setString("COMPANY_NAME", companyName);
      } else {
        rwRow.setString("COMPANY_NAME", companyName);
      }
      break;
    default:
      throw getPropertyNotAvailableException("CompanyName");
    }
  }
  public Column colCompanyName() {
    switch (curAccessType) {
    case ONEREC:
      return (rwRow==null ? curDataSets[0].getColumn("COMPANY_NAME") : rwRow.getColumn("COMPANY_NAME"));
    case LIST:
      return (rwRow==null ? curDataSets[0].getColumn("COMPANY_NAME") : rwRow.getColumn("COMPANY_NAME"));
    case NONE:
      if (sdsNone.hasColumn("CompanyName")==null) {
        Column col = new Column();
        col.setCaption("CompanyName");
        col.setColumnName("CompanyName");
        col.setDataType(com.borland.dx.dataset.Variant.STRING);
        sdsNone.addColumn(col);
      }
      return sdsNone.getColumn("CompanyName");
    default:
      return null;
    }
  }

// Id:
  public boolean isIdNull() {
    switch (curAccessType) {
    case ONEREC:
      return rwRow==null ? curDataSets[0].isNull("ID") : rwRow.isNull("ID");
    case LIST:
      return rwRow==null ? curDataSets[0].isNull("ID") : rwRow.isNull("ID");
    default:
      throw getPropertyNotAvailableException("Id");
    }
  }
  public void setIdNull() {
    switch (curAccessType) {
    case ONEREC:
      if (rwRow==null) {
        curDataSets[0].setAssignedNull("ID");
      } else {
        rwRow.setAssignedNull("ID");
      }
      break;
    case LIST:
      if (rwRow==null) {
        curDataSets[0].setAssignedNull("ID");
      } else {
        rwRow.setAssignedNull("ID");
      }
      break;
    default:
      throw getPropertyNotAvailableException("Id");
    }
  }
  public int getId() {/// ## 1
    if(isIdNull()) throw new DataSetException("Property value equals null!!!");
    switch (curAccessType) {
    case ONEREC:
      return rwRow==null ? curDataSets[0].getInt("ID") : rwRow.getInt("ID");
    case LIST:
      return rwRow==null ? curDataSets[0].getInt("ID") : rwRow.getInt("ID");
    default:
      throw getPropertyNotAvailableException("Id");
    }
  }
  public void setId(int id) {/// ## 2
    switch (curAccessType) {
    case ONEREC:
      if (rwRow==null) {
        curDataSets[0].setInt("ID", id);
      } else {
        rwRow.setInt("ID", id);
      }
      break;
    case LIST:
      if (rwRow==null) {
        curDataSets[0].setInt("ID", id);
      } else {
        rwRow.setInt("ID", id);
      }
      break;
    default:
      throw getPropertyNotAvailableException("Id");
    }
  }
  public Column colId() {
    switch (curAccessType) {
    case ONEREC:
      return (rwRow==null ? curDataSets[0].getColumn("ID") : rwRow.getColumn("ID"));
    case LIST:
      return (rwRow==null ? curDataSets[0].getColumn("ID") : rwRow.getColumn("ID"));
    case NONE:
      if (sdsNone.hasColumn("Id")==null) {
        Column col = new Column();
        col.setCaption("Id");
        col.setColumnName("Id");
        col.setDataType(com.borland.dx.dataset.Variant.INT);
        sdsNone.addColumn(col);
      }
      return sdsNone.getColumn("Id");
    default:
      return null;
    }
  }

  protected Column getColumnByProperty(String propName) {
    if (propName==null) {
        return null;
    } else if (propName.equals("Name")) {
      return colName();
    } else if (propName.equals("CompanyName")) {
      return colCompanyName();
    } else if (propName.equals("Id")) {
      return colId();
    } else {
      for (int i=0; i<curDataSets.length; i++) {
        Column col = curDataSets[i].hasColumn(propName);
        if (col!=null) return col;
      }
    }
    return null;
  }
//  import com.borland.dx.sql.dataset.Database;
//  import com.borland.dx.sql.dataset.ProcedureDataSet;
//  import com.borland.dx.dataset.StorageDataSet;
//  import com.borland.dx.dataset.ReadWriteRow;
//  import com.borland.dx.dataset.DataRow;
//  import com.borland.dx.dataset.DataSetException;
//  import com.borland.dx.dataset.Locate;
//  import java.util.Hashtable;
//  
//  private Database construct_db;
//  //protected T6467063785ChangeLog chngLog = super.getChangeLog();
//  private static T6467063785 dfltInstance_NONE = null; 
//  private static T6467063785 dfltInstance_ONEREC = null; 
//  private static T6467063785 dfltInstance_LIST = null; 
//  
//  private static Hashtable<Integer, T6467063785> htLookup = new Hashtable<Integer,T6467063785>();
//  public static T6467063785 getDfltT6467063785Lkup(Database db) {
//    T6467063785 lkupObj;
//    if (db==null) {
//      lkupObj = getDfltInstance(T6467063785AccessType.LIST);
//      db = ((ProcedureDataSet)lkupObj.getDataSetMain()).getDatabase();
//      htLookup.put(db.hashCode(), lkupObj);
//    } else {
//      if (htLookup.containsKey(db.hashCode())) {
//        lkupObj = htLookup.get(db.hashCode());
//      } else {
//        lkupObj = new T6467063785(T6467063785AccessType.LIST, db);
//        htLookup.put(db.hashCode(), lkupObj);
//      }
//    }
//    if (!lkupObj.getDataSetMain().isOpen()) lkupObj.RefreshDataSets();
//    return lkupObj;
//  }
//  
//  public static T6467063785 getDfltInstance(T6467063785AccessType accessType) {
//  switch (accessType) {
//    case ONEREC :
//      if(dfltInstance_ONEREC == null) dfltInstance_ONEREC = new T6467063785(T6467063785AccessType.ONEREC);
//      //if (!dfltInstance_ONEREC.getDataSetMain().isOpen()) dfltInstance_ONEREC.RefreshDataSets();
//      return dfltInstance_ONEREC;
//    case LIST :
//      if(dfltInstance_LIST == null) dfltInstance_LIST = new T6467063785(T6467063785AccessType.LIST);
//      //if (!dfltInstance_LIST.getDataSetMain().isOpen()) dfltInstance_LIST.RefreshDataSets();
//      return dfltInstance_LIST;
//    default:
//      if(dfltInstance_NONE == null) dfltInstance_NONE = new T6467063785(T6467063785AccessType.NONE);
//      return dfltInstance_NONE;
//   }
//  }
//   
//  public static T6467063785 getDfltInstance() {
//    return getDfltInstance(T6467063785AccessType.NONE);
//  }
//  
//  //protected StorageDataSet sdsMain = super.getDataSetMain();
//  //protected StorageDataSet sdsNone = super.getSdsNone();
//  //protected Column colName = super.colName();
//  //protected Column colCompanyName = super.colCompanyName();
//  //protected Column colId = super.colId();
//  
//  public T6467063785() {
//    //super(T6467063785AccessType.ONEREC, true);
//    //super(T6467063785AccessType.LIST, true);
//    try {
//        jbInit();
//    } catch (Exception ex) {
//      ex.printStackTrace();
//    }
//  }
//  
//  public T6467063785(T6467063785AccessType accessType) {
//    try {
//      jbInit();
//    } catch (Exception ex) {
//      ex.printStackTrace();
//    }
//    setAccessType(accessType, false);
//  }
//  
//  public T6467063785(T6467063785AccessType accessType, StorageDataSet sds) {
//    super(accessType, new StorageDataSet[] {sds});
//    try {
//      jbInit();
//    } catch (Exception ex) {
//      ex.printStackTrace();
//    }
//  }
//  
//  public T6467063785(T6467063785AccessType accessType, Database db) {
//    construct_db = db;
//    try {
//      jbInit();
//    } catch (Exception ex) {
//      ex.printStackTrace();
//    }
//    setAccessType(accessType, construct_db);
//  }
//  
//  private void lsInit() {
//    //sdsMain.setColumns(sdsMain.getColumns());
//    //sdsNone.setColumns(super.getDesignColumns());
//  }
//  
//  private void jbInit() throws Exception {
//    lsInit();
//  }
//  
//  public boolean accessOneRec_By?(String _, boolean forceRefresh) {
//    return accessOneRec_By?(_, false, forceRefresh);
//  }
//  public boolean accessOneRec_By?(String _, boolean insertRow ,boolean forceRefresh) {
//    if (getAccessType()!=T6467063785AccessType._) {
//      if (construct_db!=null) {
//        this.setAccessType(T6467063785AccessType._, construct_db);
//      } else {
//        this.setAccessType(T6467063785AccessType._, false);
//      }
//    }
//    StorageDataSet sds = getDataSetMain();
//    ReadWriteRow paramRow = sds.getProvider().getParameterRow();
//    if (!paramRow.isNull("_") && paramRow.getString("_").equals(_)) {
//      if (forceRefresh) this.RefreshDataSets();
//    } else {
//      paramRow.setString("_", _);
//      this.RefreshDataSets();
//    }
//    if(sds.rowCount()==0 && insertRow){
//      sds.insertRow(false);
//      return false;
//    }else if(sds.rowCount()>0){
//      return true;
//    }
//    return false;
//  }
//  
//  public boolean moveToRow_By?(String _) {
//    if (this.getAccessType()!=T6467063785AccessType._) {
//      throw new DataSetException("can't use moveToRow... with " + this.getAccessType());
//    }
//    String _FldName = col_().getColumnName();
//    StorageDataSet sds = getDataSetMain();
//    if (!sds.isOpen()) sds.open();
//    DataRow _dr = new DataRow(sds, new String[] {_FldName});
//    _dr.setString(_FldName, _);
//    return sds.locate(_dr, Locate.FIRST);
//  }
//  
//  protected boolean allowAccessTypeChange(T6467063785AccessType accessType) {
//    if (this == dfltInstance_ONEREC) {
//      if (accessType!=T6467063785AccessType.ONEREC) return false;
//    } else if (this == dfltInstance_LIST) {
//      if (accessType!=T6467063785AccessType.LIST) return false;
//    } else { 
//      return true;
//    }
//    return true;
//  }
//  
}
